version: '3.8'

services:
  # Service MongoDB pour production
  mongodb:
    image: mongo:7.0
    container_name: forms-mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    volumes:
      - mongodb_data_prod:/data/db
      - mongodb_config_prod:/data/configdb
    networks:
      - forms-network-prod
    # Pas de ports exposés en production

  # Service API FastAPI pour production
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forms-api-prod
    restart: always
    environment:
      # Application
      APP_NAME: ${APP_NAME}
      DEBUG: "false"

      # Database
      MONGODB_URL: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGODB_DB_NAME}?authSource=admin"
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}

      # Security
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

      # CORS
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on:
      - mongodb
    networks:
      - forms-network-prod
    # Pas de volumes en production

  # Reverse proxy Nginx
  nginx:
    image: nginx:alpine
    container_name: forms-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - forms-network-prod

networks:
  forms-network-prod:
    driver: bridge

volumes:
  mongodb_data_prod:
  mongodb_config_prod: